
if(NOT WIN32)
	string(ASCII 27 Esc)

	set(ColourReset "${Esc}[m")
	set(ColourBold  "${Esc}[1m")
	set(Red         "${Esc}[31m")
	set(Green       "${Esc}[32m")
	set(Yellow      "${Esc}[33m")
	set(Blue        "${Esc}[34m")
	set(Magenta     "${Esc}[35m")
	set(Cyan        "${Esc}[36m")
	set(White       "${Esc}[37m")
	set(BoldRed     "${Esc}[1;31m")
	set(BoldGreen   "${Esc}[1;32m")
	set(BoldYellow  "${Esc}[1;33m")
	set(BoldBlue    "${Esc}[1;34m")
	set(BoldMagenta "${Esc}[1;35m")
	set(BoldCyan    "${Esc}[1;36m")
	set(BoldWhite   "${Esc}[1;37m")
endif()

macro(print_color_summary)
	message(STATUS "${BoldBlue}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-${ColourReset}")
	message(STATUS "${BoldYellow}${PROJECT_NAME}${ColourReset}"
		" Version ${BoldYellow}${PROJECT_VERSION}${ColourReset}")
	message(STATUS "")
	message(STATUS "Build type is set to ${BoldGreen}${CMAKE_BUILD_TYPE}${ColourReset}.")
	message(STATUS "Data directory is set to ${BoldGreen}${DATADIR}${ColourReset}.")
	message(STATUS "")
	message(STATUS "Homepage: ${BoldMagenta}${PROJECT_HOMEPAGE_URL}${ColourReset}")
	message(STATUS "${BoldBlue}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-${ColourReset}")
endmacro()
